# Generated by Django 4.1.2 on 2022-10-14 08:28

from django.db import migrations, models
import sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_product_options_product_dicount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=sale.models.upload_to),
        ),
    ]
