# Generated by Django 4.1.2 on 2022-10-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dicount_price',
            new_name='discount_price',
        ),
    ]
